export const dataCard = [
  {
    id: "1",
    border: "border-primary",
    text: "text-[#FFF4E499]",
    bg: "bg-primary",
    bgButton: "bg-primary",
    separatorColor: "bg-primary",
    hoverButton: "hover:bg-[#ede3d3]",
    textButton: "text-custom-bg",
    borderButton: "border-secondary",
    plan: "Básico",
    price: "99",
    description: "para rellenar con una pequeña sentencia",
    items: [
      { iconColor: "#e5e5e5", text: "textA" },
      { iconColor: "#e5e5e5", text: "textB" },
      { iconColor: "#e5e5e5", text: "textC" },
      { iconColor: "#e5e5e5", text: "textD" },
    ],
  },
  {
    id: "2",
    border: "border-primary",
    text: "text-[#FFF4E499]",
    bg: "bg-primary",
    bgButton: "bg-primary",
    separatorColor: "bg-primary",
    hoverButton: "hover:bg-[#ede3d3]",
    textButton: "text-custom-bg",
    borderButton: "border-secondary",
    plan: "Básico",
    price: "99",
    description: "para rellenar con una pequeña sentencia",
    items: [
      { iconColor: "#e5e5e5", text: "textA" },
      { iconColor: "#e5e5e5", text: "textB" },
      { iconColor: "#e5e5e5", text: "textC" },
      { iconColor: "#e5e5e5", text: "textD" },
    ],
  },
  {
    id: "3",
    border: "border-primary",
    text: "text-[#FFF4E499]",
    bg: "bg-primary",
    bgButton: "bg-primary",
    separatorColor: "bg-primary",
    hoverButton: "hover:bg-[#ede3d3]",
    textButton: "text-custom-bg",
    borderButton: "border-secondary",
    plan: "Básico",
    price: "99",
    description: "para rellenar con una pequeña sentencia",
    items: [
      { iconColor: "#e5e5e5", text: "textA" },
      { iconColor: "#e5e5e5", text: "textB" },
      { iconColor: "#e5e5e5", text: "textC" },
      { iconColor: "#e5e5e5", text: "textD" },
    ],
  },
];
